name: CI

on:
  workflow_dispatch
# you can trigger on anything you want

jobs:
  build:
   runs-on: ubuntu-latest

   steps:
     - uses: actions/checkout@v2
     - name: Build Docker image
       run: docker build --target torchdrive_test -t torchdrive_test:latest .
     - name: Run tests inside the container
       run: docker run torchdrive-tests:latest