name: CI_cpu

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - "*"
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install lanelet2 pytest && pip install .

    - name: Run tests
      run: |
        pytest -s -m "not depends_on_cuda and not depends_on_pytorch3d and not depends_on_nvdiffrast" tests
